export type * from "./schemas/trading";

export const TRADING_KEYS = {
  analytics: "analytics",
  historySummary: "history-summary",
  tradeMetadata: "trade-metadata",
  marketSnapshot: "market-snapshot",
  transferStatus: "transfer-status",
  archetypes: "archetypes",
  measurementState: "measurement-state",
  regime: "regime",
  patterns: "patterns",
  accuracy: "accuracy",
  fingerprint: "fingerprint",
  trustAnalysis: "trust-analysis",
  decisionsSummary: "decisions-summary",
  volSharpe: "vol-sharpe",
  vrpAttribution: "vrp-attribution",
  regimeVrp: "regime-vrp",
  dispersionFollow: "dispersion-follow",
  correlation: "correlation",
  counterfactualDefault: "counterfactual-default",
  evolution: "evolution",
  trajectory: "trajectory",
  conservation: "conservation",
  centroidHistorySummary: "centroid-history-summary",
  auditTrailSummary: "audit-trail-summary",
  regimeStatus: "regime-status",
  regimeAnalytics: "regime-analytics",
  promotion: "promotion",
  rejectionSummary: "rejection-summary",
  transfer: "transfer",
  execution: "execution",
  webhookHistory: "webhook-history",
  cohortStatus: "cohort-status",
  vix: "vix",
  journalTradesSummary: "journal-trades-summary",
  analyticsByCategory: "analytics-by-category",
  analyticsBySubcategory: "analytics-by-subcategory",
  regimeHistory: "regime-history",
  correlationConfig: "correlation-config",
  regimeAnalyticsSummary: "regime-analytics-summary",
  iks: "iks",
  regimeCurrent: "regime-current",
  regimePerformance: "regime-performance",
  evolutionPromoted: "evolution-promoted",
} as const;

export type TradingKey = typeof TRADING_KEYS[keyof typeof TRADING_KEYS];

export const DASHBOARD_KEYS: readonly TradingKey[] = [
  TRADING_KEYS.analytics,
  TRADING_KEYS.historySummary,
  TRADING_KEYS.tradeMetadata,
  TRADING_KEYS.marketSnapshot,
  TRADING_KEYS.transferStatus,
  TRADING_KEYS.archetypes,
  TRADING_KEYS.measurementState,
  TRADING_KEYS.regime,
  TRADING_KEYS.regimeCurrent,
  TRADING_KEYS.regimeHistory,
  TRADING_KEYS.regimePerformance,
  TRADING_KEYS.patterns,
  TRADING_KEYS.accuracy,
];

export const PERFORMANCE_KEYS: readonly TradingKey[] = [
  TRADING_KEYS.analytics,
  TRADING_KEYS.trajectory,
  TRADING_KEYS.conservation,
  TRADING_KEYS.centroidHistorySummary,
  TRADING_KEYS.auditTrailSummary,
  TRADING_KEYS.regimeStatus,
  TRADING_KEYS.regimeAnalytics,
  TRADING_KEYS.promotion,
  TRADING_KEYS.rejectionSummary,
  TRADING_KEYS.transfer,
  TRADING_KEYS.evolution,
  TRADING_KEYS.iks,
  TRADING_KEYS.execution,
  TRADING_KEYS.webhookHistory,
  TRADING_KEYS.cohortStatus,
  TRADING_KEYS.vix,
];

export const ANALYSIS_KEYS: readonly TradingKey[] = [
  TRADING_KEYS.analytics,
  TRADING_KEYS.fingerprint,
  TRADING_KEYS.trustAnalysis,
  TRADING_KEYS.regime,
  TRADING_KEYS.patterns,
  TRADING_KEYS.decisionsSummary,
  TRADING_KEYS.volSharpe,
  TRADING_KEYS.vrpAttribution,
  TRADING_KEYS.regimeVrp,
  TRADING_KEYS.dispersionFollow,
  TRADING_KEYS.correlation,
  TRADING_KEYS.counterfactualDefault,
  TRADING_KEYS.regimeHistory,
  TRADING_KEYS.regimeCurrent,
  TRADING_KEYS.regimePerformance,
  TRADING_KEYS.correlationConfig,
  TRADING_KEYS.regimeAnalyticsSummary,
  TRADING_KEYS.evolution,
  TRADING_KEYS.evolutionPromoted,
];

export const JOURNAL_KEYS: readonly TradingKey[] = [
  TRADING_KEYS.journalTradesSummary,
  TRADING_KEYS.analyticsByCategory,
  TRADING_KEYS.analyticsBySubcategory,
];

export const LOG_TRADE_KEYS: readonly TradingKey[] = [
  TRADING_KEYS.marketSnapshot,
  TRADING_KEYS.fingerprint,
  TRADING_KEYS.analytics,
];
