"""Generate TypeScript tab-state response types from Pydantic schemas."""

from __future__ import annotations

import sys
import importlib
from pathlib import Path
from typing import Any

from pydantic import BaseModel, RootModel


REPO_ROOT = Path(__file__).resolve().parents[1]
TRADING_BACKEND = REPO_ROOT / "apps" / "trading" / "backend"

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
if str(TRADING_BACKEND) not in sys.path:
    sys.path.insert(0, str(TRADING_BACKEND))

from copilot_sdk.state.schemas import shared as shared_schemas  # noqa: E402


HEADER = "// GENERATED by scripts/generate_tab_state_types.py. Do not edit by hand.\n\n"


SHARED_MODELS: list[type[BaseModel]] = [
    shared_schemas.TrajectoryResponse,
    shared_schemas.AnalyticsResponse,
    shared_schemas.ConservationResponse,
    shared_schemas.CohortStatusResponse,
    shared_schemas.FingerprintResponse,
]


def ts_name(model: type[BaseModel]) -> str:
    return model.__name__


def ts_type(annotation: Any) -> str:
    text = str(annotation)
    origin = getattr(annotation, "__origin__", None)
    args = getattr(annotation, "__args__", ())
    if annotation in {str, "str"}:
        return "string"
    if annotation in {int, float}:
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is Any:
        return "unknown"
    if origin in {list, tuple} and args:
        return f"{ts_type(args[0])}[]"
    if origin is dict:
        return "Record<string, unknown>"
    if origin is None and isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation.__name__
    if "NoneType" in text or " | None" in text:
        non_null = [arg for arg in args if getattr(arg, "__name__", "") != "NoneType"]
        if len(non_null) == 1:
            return ts_type(non_null[0])
    if "|" in text:
        return "unknown"
    return "unknown"


def emit_model(model: type[BaseModel]) -> str:
    if issubclass(model, RootModel):
        field = model.model_fields["root"]
        return f"export type {ts_name(model)} = {ts_type(field.annotation)};\n"
    lines = [f"export interface {ts_name(model)} {{"]
    for name, field in model.model_fields.items():
        prop = field.alias or name
        optional = "?" if not field.is_required() else ""
        lines.append(f"  {snake_to_camel(prop)}{optional}: {ts_type(field.annotation)};")
    lines.append("  [key: string]: unknown;")
    lines.append("}\n")
    return "\n".join(lines)


def snake_to_camel(value: str) -> str:
    parts = value.split("_")
    return parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])


def render_shared() -> str:
    return HEADER + "\n".join(emit_model(model) for model in SHARED_MODELS)


def _load_trading_schema_models() -> tuple[Any, dict[Any, type[BaseModel]]]:
    original_path = list(sys.path)
    original_app_modules = {
        name: module
        for name, module in sys.modules.items()
        if name == "app" or name.startswith("app.")
    }
    try:
        for name in list(sys.modules):
            if name == "app" or name.startswith("app."):
                sys.modules.pop(name, None)
        sys.path.insert(0, str(TRADING_BACKEND))
        importlib.invalidate_caches()
        from app.state.key_manifest import TradingKey
        from app.state.schemas.trading import TRADING_SCHEMA_BY_KEY

        return TradingKey, dict(TRADING_SCHEMA_BY_KEY)
    finally:
        for name in list(sys.modules):
            if name == "app" or name.startswith("app."):
                sys.modules.pop(name, None)
        sys.path[:] = original_path
        sys.modules.update(original_app_modules)


def render_trading() -> str:
    trading_key, trading_schema_by_key = _load_trading_schema_models()

    seen: set[type[BaseModel]] = set()
    ordered: list[type[BaseModel]] = []

    def add_model(model: type[BaseModel]) -> None:
        if model in seen:
            return
        seen.add(model)
        for field in getattr(model, "model_fields", {}).values():
            for nested in nested_models(field.annotation):
                add_model(nested)
        ordered.append(model)

    for key in trading_key:
        add_model(trading_schema_by_key[key])
    return HEADER + "\n".join(emit_model(model) for model in ordered)


def nested_models(annotation: Any) -> list[type[BaseModel]]:
    origin = getattr(annotation, "__origin__", None)
    args = getattr(annotation, "__args__", ())
    if origin in {list, tuple} and args:
        return nested_models(args[0])
    if " | None" in str(annotation) and args:
        result: list[type[BaseModel]] = []
        for arg in args:
            if getattr(arg, "__name__", "") != "NoneType":
                result.extend(nested_models(arg))
        return result
    if origin is None and isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return [annotation]
    return []


def write_outputs() -> None:
    outputs = {
        REPO_ROOT / "copilot_sdk" / "frontend" / "providers" / "schemas" / "shared.ts": render_shared(),
        REPO_ROOT / "apps" / "trading" / "frontend" / "src" / "state" / "schemas" / "trading.ts": render_trading(),
    }
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(REPO_ROOT)}")


def main() -> None:
    write_outputs()


if __name__ == "__main__":
    main()
