// GENERATED by scripts/generate_tab_state_types.py. Do not edit by hand.

export interface TrajectoryResponse {
  points?: unknown[];
  currentIks?: unknown;
  currentWinRate?: unknown;
  decisionsTotal?: number;
  daysActive?: unknown;
  engine?: unknown;
  [key: string]: unknown;
}

export interface AnalyticsResponse {
  totalTrades?: number;
  closedTrades?: number;
  portfolioSummary?: Record<string, unknown>;
  portfolioConcentration?: Record<string, unknown>;
  categoryCounts?: Record<string, unknown>;
  thesisCounts?: Record<string, unknown>;
  thesisBreakdown?: Record<string, unknown>;
  riskManagement?: Record<string, unknown>;
  researchImpact?: Record<string, unknown>;
  openPositions?: unknown;
  calendarHeatmap?: unknown;
  rolling10?: Record<string, unknown>[];
  regimeAnalysis?: Record<string, unknown>;
  contrastCard?: Record<string, unknown>;
  counterfactual?: Record<string, unknown>;
  seedFile?: string;
  provenance?: string;
  source?: string;
  [key: string]: unknown;
}

export interface ConservationResponse {
  domain?: string;
  engine?: unknown;
  signal?: unknown;
  status?: string;
  passed?: boolean;
  thetaMin?: unknown;
  headroom?: unknown;
  penaltyRatio?: unknown;
  verifiedCount?: number;
  totalDecisions?: number;
  correctCount?: number;
  [key: string]: unknown;
}

export interface CohortStatusResponse {
  state?: string;
  real?: Record<string, unknown>;
  instrument?: Record<string, unknown>;
  structure?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface FingerprintResponse {
  factors?: unknown[];
  perCategoryPrecision?: Record<string, unknown>;
  decisionsAnalyzed?: number;
  overallWinRate?: unknown;
  skippedDecisions?: number;
  engine?: unknown;
  [key: string]: unknown;
}
