// GENERATED by scripts/generate_tab_state_types.py. Do not edit by hand.

export interface AnalyticsResponse {
  totalTrades?: number;
  closedTrades?: number;
  portfolioSummary?: Record<string, unknown>;
  portfolioConcentration?: Record<string, unknown>;
  categoryCounts?: Record<string, unknown>;
  thesisCounts?: Record<string, unknown>;
  thesisBreakdown?: Record<string, unknown>;
  riskManagement?: Record<string, unknown>;
  researchImpact?: Record<string, unknown>;
  openPositions?: unknown;
  calendarHeatmap?: unknown;
  rolling10?: Record<string, unknown>[];
  regimeAnalysis?: Record<string, unknown>;
  contrastCard?: Record<string, unknown>;
  counterfactual?: Record<string, unknown>;
  seedFile?: string;
  provenance?: string;
  source?: string;
  [key: string]: unknown;
}

export interface HistorySummaryResponse {
  decisions?: Record<string, unknown>[];
  total?: number;
  bounded?: boolean;
  engine?: unknown;
  [key: string]: unknown;
}

export type TradeMetadataResponse = Record<string, unknown>;

export interface MarketSnapshotResponse {
  vix?: Record<string, unknown>;
  spy?: Record<string, unknown>;
  source?: string;
  sector?: Record<string, unknown>;
  provenance?: Record<string, unknown>;
  asOf?: string;
  rsi?: number;
  above50ma?: boolean;
  volumeRank?: number;
  marketCapB?: number;
  sourceDetail?: string;
  [key: string]: unknown;
}

export interface TransferStatusResponse {
  warmStarted?: boolean;
  sourceCopilot?: string;
  sourceAccuracy?: number;
  patternsTransferred?: number;
  categoriesTransferred?: number;
  provenance?: string;
  status?: string;
  domain?: string;
  ownFingerprintPresent?: boolean;
  availableDomains?: string[];
  opportunityCount?: number;
  opportunities?: Record<string, unknown>[];
  warnings?: unknown[];
  availableTransfers?: Record<string, unknown>[];
  [key: string]: unknown;
}

export type ArchetypesResponse = unknown;

export interface MeasurementStateResponse {
  engine?: unknown;
  state?: string;
  message?: string;
  accuracy?: number;
  iks?: number;
  decisionsVerified?: number;
  decisionsNeeded?: number;
  armsMeasured?: number;
  armsTotal?: number;
  provenance?: string;
  [key: string]: unknown;
}

export interface RegimeResponse {
  currentRegime?: string;
  previousRegime?: string;
  regimeBreakActive?: boolean;
  decisionsInNewRegime?: number;
  decisionsToStabilize?: number;
  autonomyLevel?: string;
  restrictions?: string[];
  current?: Record<string, unknown>;
  accuracyByCategory?: Record<string, unknown>;
  recommendations?: Record<string, unknown>[];
  [key: string]: unknown;
}

export interface PatternsResponse {
  patterns?: Record<string, unknown>[];
  totalTrades?: number;
  message?: string;
  totalPatternsDetected?: number;
  totalTradesAnalyzed?: number;
  activePatterns?: number;
  patternsByCategory?: Record<string, unknown>;
  mostSevere?: string;
  [key: string]: unknown;
}

export interface AccuracyResponse {
  categories?: Record<string, unknown>[];
  overallVerified?: number;
  threshold?: number;
  [key: string]: unknown;
}

export interface FingerprintResponse {
  factors?: unknown[];
  perCategoryPrecision?: Record<string, unknown>;
  decisionsAnalyzed?: number;
  overallWinRate?: unknown;
  skippedDecisions?: number;
  engine?: unknown;
  [key: string]: unknown;
}

export interface TrustAnalysisResponse {
  factors?: unknown[];
  factorDetails?: Record<string, unknown>[];
  factorNames?: string[];
  trustScores?: Record<string, unknown>;
  mode?: string;
  phase?: string;
  availableCategories?: string[];
  implemented?: string[];
  topSignal?: string;
  noiseSignals?: string[];
  heroInsight?: string;
  perCategory?: unknown;
  decisionsUntilDk?: number;
  totalTrades?: number;
  [key: string]: unknown;
}

export interface DecisionsSummaryResponse {
  decisions?: Record<string, unknown>[];
  total?: number;
  limit?: number;
  [key: string]: unknown;
}

export interface VolSharpeResponse {
  naiveQualityScore?: number;
  qualityAdjustedScore?: number;
  inflation?: number;
  nDecisions?: number;
  decisionsUntilMeasured?: number;
  dayZero?: boolean;
  provenance?: string;
  substantiation?: unknown;
  status?: string;
  overallQualityScore?: number;
  overallQualityAdjusted?: number;
  clusters?: Record<string, unknown>[];
  minDecisionsPerCluster?: number;
  source?: string;
  analyticsProvenance?: string;
  [key: string]: unknown;
}

export interface VrpAttributionResponse {
  provenance?: string;
  substantiation?: unknown;
  dayZero?: boolean;
  decisionsUntilMeasured?: number;
  status?: string;
  vrpSpreadMean?: number;
  vrpSpreadCurrent?: number;
  classification?: string;
  ivMean?: number;
  rvMean?: number;
  nEligible?: number;
  nExcludedMissingIvRv?: number;
  minObservations?: number;
  source?: string;
  analyticsProvenance?: string;
  tailAttribution?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface RegimeVrpResponse {
  regimes?: unknown;
  nDecisions?: number;
  provenance?: string;
  substantiation?: unknown;
  dayZero?: boolean;
  decisionsUntilMeasured?: number;
  [key: string]: unknown;
}

export interface DispersionFollowResponse {
  followRate?: number;
  signalsFired?: number;
  followed?: number;
  skipped?: number;
  skippedValue?: number;
  provenance?: string;
  substantiation?: unknown;
  dayZero?: boolean;
  decisionsUntilMeasured?: number;
  [key: string]: unknown;
}

export interface CorrelationPairResponse {
  tickerA?: string;
  tickerB?: string;
  correlation?: number;
  [key: string]: unknown;
}

export interface CorrelationAlertResponse {
  level?: string;
  message?: string;
  value?: number;
  tickerA?: string;
  tickerB?: string;
  tickers?: string[];
  correlation?: number;
  [key: string]: unknown;
}

export interface CorrelationResponse {
  matrix?: unknown;
  correlations?: unknown;
  tickers?: string[];
  pairs?: CorrelationPairResponse[];
  avgCorrelation?: number;
  maxPair?: CorrelationPairResponse;
  alerts?: CorrelationAlertResponse[];
  windowDays?: number;
  source?: string;
  reason?: string;
  nDecisions?: number;
  dayZero?: boolean;
  decisionsUntilMeasured?: number;
  provenance?: string;
  rhoBar?: number;
  effectiveMultiplier?: number;
  nEffectiveBets?: number;
  tailGap?: unknown;
  recommendations?: string[];
  [key: string]: unknown;
}

export interface CounterfactualDefaultResponse {
  baseScore?: number;
  perturbedScore?: number;
  delta?: number;
  perturbedFactor?: string;
  baseAction?: string;
  perturbedAction?: string;
  provenance?: string;
  [key: string]: unknown;
}

export type EvolutionResponse = unknown;

export interface TrajectoryResponse {
  points?: unknown[];
  currentIks?: unknown;
  currentWinRate?: unknown;
  decisionsTotal?: number;
  daysActive?: unknown;
  engine?: unknown;
  [key: string]: unknown;
}

export interface ConservationResponse {
  domain?: string;
  engine?: unknown;
  signal?: unknown;
  status?: string;
  passed?: boolean;
  thetaMin?: unknown;
  headroom?: unknown;
  penaltyRatio?: unknown;
  reason?: string;
  alpha?: unknown;
  q?: unknown;
  V?: number;
  baseline?: unknown;
  baselineQ?: unknown;
  categoriesTotal?: number;
  categoriesWithData?: number;
  verifiedCount?: number;
  totalDecisions?: number;
  correctCount?: number;
  totalCategories?: number;
  relativeTrigger?: unknown;
  relativeTriggerRatio?: unknown;
  [key: string]: unknown;
}

export interface CentroidHistorySummaryResponse {
  checkpoints?: Record<string, unknown>[];
  total?: number;
  [key: string]: unknown;
}

export interface AuditTrailSummaryResponse {
  trails?: Record<string, unknown>[];
  total?: number;
  [key: string]: unknown;
}

export interface RegimeStatusResponse {
  currentRegime?: string;
  previousRegime?: string;
  regimeBreakActive?: boolean;
  decisionsInNewRegime?: number;
  decisionsToStabilize?: number;
  autonomyLevel?: string;
  restrictions?: string[];
  current?: Record<string, unknown>;
  accuracyByCategory?: Record<string, unknown>;
  recommendations?: Record<string, unknown>[];
  [key: string]: unknown;
}

export interface RegimeAnalyticsResponse {
  regimes?: Record<string, unknown>;
  totalDecisions?: number;
  regimeCount?: number;
  [key: string]: unknown;
}

export type PromotionResponse = Record<string, unknown>[];

export interface RejectionSummaryResponse {
  totalTested?: number;
  totalPromoted?: number;
  totalRejected?: number;
  rejectionBreakdown?: Record<string, unknown>;
  rejectedVariants?: Record<string, unknown>[];
  provenance?: string;
  [key: string]: unknown;
}

export interface TransferResponse {
  warmStarted?: boolean;
  sourceCopilot?: string;
  sourceAccuracy?: number;
  patternsTransferred?: number;
  categoriesTransferred?: number;
  provenance?: string;
  status?: string;
  domain?: string;
  ownFingerprintPresent?: boolean;
  availableDomains?: string[];
  opportunityCount?: number;
  opportunities?: Record<string, unknown>[];
  warnings?: unknown[];
  availableTransfers?: Record<string, unknown>[];
  [key: string]: unknown;
}

export interface BrokerExecutionSummaryResponse {
  broker?: string;
  tradeCount?: number;
  avgSlippage?: number;
  fillRate?: number;
  medianSlippage?: number;
  totalSlippageCost?: number;
  avgFillTimeSeconds?: number;
  [key: string]: unknown;
}

export interface ExecutionResponse {
  summary?: unknown;
  brokers?: BrokerExecutionSummaryResponse[];
  bestBroker?: string;
  annualSavingsEstimate?: number;
  recommendation?: string;
  [key: string]: unknown;
}

export type WebhookHistoryResponse = unknown;

export interface CohortStatusResponse {
  state?: string;
  real?: Record<string, unknown>;
  instrument?: Record<string, unknown>;
  structure?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface VixResponse {
  status?: string;
  matrix?: Record<string, unknown>;
  bestBucket?: unknown;
  worstBucket?: unknown;
  totalAnalyzed?: number;
  totalSkipped?: number;
  holdLabels?: Record<string, unknown>;
  vixLabels?: Record<string, unknown>;
  recommendations?: string[];
  [key: string]: unknown;
}

export interface JournalTradesSummaryResponse {
  trades?: Record<string, unknown>[];
  count?: number;
  total?: number;
  filtersApplied?: Record<string, unknown>;
  aggregate?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface AnalyticsByCategoryResponse {
  groupBy?: string;
  groups?: Record<string, unknown>[];
  total?: number;
  [key: string]: unknown;
}

export interface AnalyticsBySubcategoryResponse {
  groupBy?: string;
  groups?: Record<string, unknown>[];
  total?: number;
  [key: string]: unknown;
}

export type RegimeHistoryResponse = unknown;

export interface CorrelationConfigResponse {
  window?: number;
  [key: string]: unknown;
}

export interface RegimeAnalyticsSummaryResponse {
  regimes?: Record<string, unknown>;
  totalDecisions?: number;
  regimeCount?: number;
  [key: string]: unknown;
}

export interface IksResponse {
  iks?: number;
  [key: string]: unknown;
}

export interface RegimeCurrentResponse {
  currentRegime?: string;
  previousRegime?: string;
  regimeBreakActive?: boolean;
  decisionsInNewRegime?: number;
  decisionsToStabilize?: number;
  autonomyLevel?: string;
  restrictions?: string[];
  regime?: string;
  confidence?: number;
  vix?: number;
  adx?: number;
  nearBoundary?: boolean;
  hurst?: number;
  volState?: string;
  vixPercentile?: number;
  timestamp?: string;
  source?: string;
  [key: string]: unknown;
}

export interface RegimePerformanceResponse {
  regimes?: Record<string, unknown>;
  totalDecisions?: number;
  regimeCount?: number;
  perRegimeAccuracy?: Record<string, unknown>;
  currentRegime?: string;
  edgeCategories?: Record<string, unknown>[];
  recommendation?: string;
  observation?: string;
  [key: string]: unknown;
}

export interface EvolutionPromotedResponse {
  domain?: string;
  promoted?: Record<string, unknown>[];
  [key: string]: unknown;
}
